version: '3'
services:
  strapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: strapi_database  # Updated with the name of the database service
      DATABASE_PORT: 5432
      DATABASE_NAME: strapidb
      DATABASE_USERNAME: strapi_user  # Updated username
      DATABASE_PASSWORD: strapi_password  # Updated password
      DATABASE_SSL: 'false'
      NODE_ENV: development
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
      - ./tmp:/opt/.tmp
    networks:
      - strapi
    depends_on:
      - strapi_database  # Uncomment to specify the dependency

  strapi_database:
    container_name: strapi_database
    platform: linux/amd64  # For platform error on Apple M1 chips
    restart: unless-stopped
    #env_file: .env
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: strapi_user
      POSTGRES_PASSWORD: strapi_password
      POSTGRES_DB: strapidb
    volumes:
      - strapi-data:/var/lib/postgresql/data

    ports:
      - "5432:5432"
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge

